import { beforeAll, describe, expect, test } from 'bun:test';
import { app } from '@app/api/app';
import { runSeed } from '@core/auth';
import { unsafeAcrossTenants } from '@core/db';

/** Generated by modgen: CRUD of notes through the real app (INTEGRATION=1). */
const enabled = process.env.INTEGRATION === '1';
const ORIGIN = 'http://api.test';
const TOKEN = 'C'.repeat(43);
const run = Date.now();
const email = `hello-${run}@example.test`;
const password = 'a generated module password';
const call = (path: string, init: RequestInit = {}, cookies: string[] = []) => {
  const headers = new Headers(init.headers);
  headers.set('origin', ORIGIN);
  headers.set('cookie', [`dab_csrf=${TOKEN}`, ...cookies].join('; '));
  headers.set('x-csrf-token', TOKEN);
  headers.set('x-forwarded-for', `10.99.${Math.floor(run / 1000) % 250}.${run % 250}`);
  if (init.body && !headers.has('content-type')) headers.set('content-type', 'application/json');
  return app.handle(new Request(`${ORIGIN}${path}`, { ...init, headers }));
};
const json = (r: Response) =>
  r.json() as Promise<{ success: boolean; data?: Record<string, unknown> }>;

describe.skipIf(!enabled)('Hello module CRUD', () => {
  let admin = '';
  beforeAll(async () => {
    if (!enabled) return;
    await runSeed(unsafeAcrossTenants(), { adminEmail: email, adminPassword: password });
    const res = await call('/v1/auth/login', {
      method: 'POST',
      body: JSON.stringify({ email, password }),
    });
    admin =
      res.headers
        .getSetCookie()
        .find((c) => c.startsWith('dab_session='))
        ?.split(';')[0] ?? '';
  });
  test('create → read → update → delete', async () => {
    const created = await call(
      '/v1/m/hello/notes',
      {
        method: 'POST',
        body: JSON.stringify({ title: 'Contoh title', body: 'Contoh body', pinned: true }),
      },
      [admin],
    );
    expect(created.status).toBe(201);
    const id = String((await json(created)).data?.id);
    expect((await call(`/v1/m/hello/notes/${id}`, {}, [admin])).status).toBe(200);
    const list = await json(await call('/v1/m/hello/notes', {}, [admin]));
    expect((list.data as unknown as { id: string }[]).some((r) => r.id === id)).toBe(true);
    expect(
      (
        await call(
          `/v1/m/hello/notes/${id}`,
          { method: 'PUT', body: JSON.stringify({ title: 'Diubah' }) },
          [admin],
        )
      ).status,
    ).toBe(200);
    expect((await call(`/v1/m/hello/notes/${id}`, { method: 'DELETE' }, [admin])).status).toBe(200);
    expect((await call(`/v1/m/hello/notes/${id}`, {}, [admin])).status).toBe(404);
    expect((await call('/v1/m/hello/notes')).status).toBe(401); // anonymous refused
  });
});
