/**
 * Module generator spec (PRD G-4, G-12). Parsed from CLI flags or interactive prompts, rendered by
 * templates.ts into a complete module: tables, permissions, menu, config, i18n, API with schemas,
 * dashboard pages (DataTable + FormBuilder), widget, hook, job, seed, and an integration test.
 */
export type FieldType = 'string' | 'text' | 'number' | 'boolean' | 'date' | 'select';

export interface FieldSpec {
  readonly name: string; // snake_case column / camelCase prop derived
  readonly type: FieldType;
  readonly required: boolean;
  readonly options?: readonly string[]; // select
  readonly max?: number;
}

export interface ModuleSpec {
  /** Folder-cased module name, e.g. `Inventory`. */
  readonly name: string;
  /** Namespace, e.g. `inventory`. */
  readonly ns: string;
  /** Singular resource, e.g. `item`. */
  readonly resource: string;
  /** Plural for routes/tables, e.g. `items`. */
  readonly plural: string;
  readonly fields: readonly FieldSpec[];
  /** Also generate a public page (extension point 13) at `/<ns>`. */
  readonly withPublic: boolean;
  readonly description: { id: string; en: string };
}

export const MODULE_NAME = /^[A-Z][A-Za-z0-9]*$/;
export const IDENT = /^[a-z][a-z0-9_]*$/;

export function toNs(name: string): string {
  return name.toLowerCase();
}
export function pluralize(word: string): string {
  if (/(s|x|z|ch|sh)$/.test(word)) return `${word}es`;
  if (/[^aeiou]y$/.test(word)) return `${word.slice(0, -1)}ies`;
  return `${word}s`;
}
export function camel(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
}
export function title(s: string): string {
  return s.replace(/_/g, ' ').replace(/^\w/, (c) => c.toUpperCase());
}

/** `name:string!,price:number,active:boolean,notes:text,kind:select(a|b|c)` */
export function parseFields(spec: string): FieldSpec[] {
  const out: FieldSpec[] = [];
  for (const raw of spec
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)) {
    const m = /^([a-z][a-z0-9_]*):(string|text|number|boolean|date|select)(\(([^)]*)\))?(!?)$/.exec(
      raw,
    );
    if (!m)
      throw new Error(`field "${raw}" tidak valid — bentuk: nama:tipe[!] atau nama:select(a|b)[!]`);
    const [, name, type, , opts, bang] = m;
    if (
      ['id', 'client_id', 'status_id', 'created_at', 'updated_at', 'deleted_at'].includes(
        name ?? '',
      )
    ) {
      throw new Error(`field "${name}" adalah kolom kontrak — sudah ada otomatis`);
    }
    const field: FieldSpec = {
      name: name ?? '',
      type: type as FieldType,
      required: bang === '!',
      ...(type === 'select'
        ? {
            options: (opts ?? '')
              .split('|')
              .map((o) => o.trim())
              .filter(Boolean),
          }
        : {}),
      ...(type === 'string' ? { max: 191 } : {}),
    };
    if (field.type === 'select' && !field.options?.length)
      throw new Error(`field "${name}": select butuh pilihan, mis. kind:select(a|b)`);
    out.push(field);
  }
  if (!out.length) throw new Error('minimal satu field');
  if (!out.some((f) => f.name === 'name' || (f.type === 'string' && f.required))) {
    throw new Error('butuh satu field string wajib sebagai judul baris, mis. name:string!');
  }
  return out;
}

export function makeSpec(input: {
  name: string;
  resource?: string;
  fields: string;
  withPublic?: boolean;
  description?: string;
}): ModuleSpec {
  if (!MODULE_NAME.test(input.name))
    throw new Error(`nama modul "${input.name}" harus PascalCase (mis. Inventory)`);
  const ns = toNs(input.name);
  const resource = (input.resource ?? ns).toLowerCase();
  if (!IDENT.test(resource)) throw new Error(`resource "${resource}" harus snake_case`);
  return {
    name: input.name,
    ns,
    resource,
    plural: pluralize(resource),
    fields: parseFields(input.fields),
    withPublic: !!input.withPublic,
    description: {
      id: input.description ?? `Modul ${input.name} (dibuat bun modgen)`,
      en: input.description ?? `${input.name} module (generated by bun modgen)`,
    },
  };
}
