import { camel, type FieldSpec, type ModuleSpec, title } from './spec.ts';

/**
 * Templates for `bun modgen` (G-4) and `bun create module` (G-12). One function per file; the
 * result is a map of relative path → content. The generated module uses ONLY the public contract
 * (`@core/module-kit`, `@core/db`, `@core/contracts`, `@app/api/*` plugins) — nothing in core.
 */
export type Files = Record<string, string>;

const col = (f: FieldSpec): string => {
  const base =
    f.type === 'string'
      ? `col.varchar(${f.max ?? 191})`
      : f.type === 'text'
        ? 'col.text()'
        : f.type === 'number'
          ? 'col.int()'
          : f.type === 'boolean'
            ? 'col.boolean().default(false)'
            : f.type === 'date'
              ? 'col.datetime()'
              : `col.identifier(64)`;
  return f.required || f.type === 'boolean' ? base : `${base}.nullable()`;
};
const tbox = (f: FieldSpec): string => {
  const inner =
    f.type === 'string'
      ? `t.String({ minLength: 1, maxLength: ${f.max ?? 191} })`
      : f.type === 'text'
        ? 't.String({ maxLength: 20000 })'
        : f.type === 'number'
          ? 't.Number()'
          : f.type === 'boolean'
            ? 't.Boolean()'
            : f.type === 'date'
              ? "t.String({ format: 'date' })"
              : `t.Union([${(f.options ?? []).map((o) => `t.Literal('${o}')`).join(', ')}])`;
  return f.required ? inner : `t.Optional(t.Nullable(${inner}))`;
};
const tsType = (f: FieldSpec): string =>
  f.type === 'number'
    ? 't.Nullable(t.Number())'
    : f.type === 'boolean'
      ? 't.Boolean()'
      : 't.Nullable(t.String())';
const fieldDef = (f: FieldSpec): string => {
  const base = `name: '${camel(f.name)}', label: '${title(f.name)}'`;
  switch (f.type) {
    case 'string':
      return `{ ${base}, type: 'string', ${f.required ? 'required: true, ' : ''}maxlength: ${f.max ?? 191} }`;
    case 'text':
      return `{ ${base}, type: 'text', rows: 3 }`;
    case 'number':
      return `{ ${base}, type: 'number'${f.required ? ', required: true' : ''} }`;
    case 'boolean':
      return `{ ${base}, type: 'boolean' }`;
    case 'date':
      return `{ ${base}, type: 'date'${f.required ? ', required: true' : ''} }`;
    case 'select':
      return `{ ${base}, type: 'select', ${f.required ? 'required: true, ' : ''}options: [${(f.options ?? []).map((o) => `{ value: '${o}', label: '${title(o)}' }`).join(', ')}] }`;
  }
};

export function renderModule(s: ModuleSpec): Files {
  const { name, ns, resource, plural, fields } = s;
  const Res = title(resource).replace(/ /g, '');
  const table = `${ns}_${plural}`;
  const tableVar = camel(table);
  const perm = `${ns}.${resource}`;
  const titleField =
    fields.find((f) => f.name === 'name') ??
    fields.find((f) => f.type === 'string' && f.required) ??
    fields[0];
  const titleProp = camel(titleField?.name ?? 'name');
  const files: Files = {};

  files['module.json'] =
    `${JSON.stringify({ name, version: '0.1.0', description: s.description, engines: { core: '>=0.0.0' } }, null, 2)}\n`;
  files['package.json'] = `${JSON.stringify(
    {
      name: `@modules/${ns}`,
      version: '0.1.0',
      private: true,
      type: 'module',
      description: `${name} module — generated by bun modgen; edit freely, it is yours`,
      scripts: { typecheck: 'bun run --cwd ../.. bootstrap >/dev/null && tsc -p tsconfig.json' },
      dependencies: {
        '@app/api': 'workspace:*',
        '@core/auth': 'workspace:*',
        '@core/contracts': 'workspace:*',
        '@core/db': 'workspace:*',
        '@core/logger': 'workspace:*',
        '@core/module-kit': 'workspace:*',
        elysia: '^1.4.0',
      },
      devDependencies: { '@sveltejs/kit': '^2.70.0', svelte: '^5.40.0' },
    },
    null,
    2,
  )}\n`;
  files['tsconfig.json'] =
    `${JSON.stringify({ extends: '../../tsconfig.base.json', compilerOptions: { noEmit: true }, include: ['**/*.ts'], exclude: ['node_modules', 'web/**'] }, null, 2)}\n`;

  files['db/tables.ts'] = `import { col, defineTable } from '@core/db';
import { defineTables } from '@core/module-kit';

/** Tables (extension point 1). Tenant-scoped: every row carries client_id and every query goes through the facade (B-3). */
export default defineTables('${name}', [
  defineTable({
    name: '${table}',
    tenant: true,
    columns: {
${fields.map((f) => `      ${f.name}: ${col(f)},`).join('\n')}
    },
    indexes: [{ columns: ['client_id', 'created_at'] }],
  }),
]);
`;
  files['permissions.ts'] = `import { CORE_ACTIONS, definePermissions } from '@core/module-kit';

/** Permissions (extension point 5): \`${perm}.read|create|edit|manage\`. */
export default definePermissions('${name}', [
  { resource: '${perm}', actions: CORE_ACTIONS, name: { id: '${title(plural)}', en: '${title(plural)}' } },
]);
`;
  files['menu.ts'] = `import { defineMenu } from '@core/module-kit';

/** Menu (extension point 4). */
export default defineMenu('${name}', [
  { id: '${ns}.${plural}', label: { id: '${title(plural)}', en: '${title(plural)}' }, href: '/m/${ns}/${plural}', icon: 'list', permission: '${perm}.read', order: 200 },
]);
`;
  files['config.ts'] = `import { defineConfig } from '@core/module-kit';

/** Configuration (extension point 6) — appears in Settings automatically. */
export default defineConfig('${name}', [
  {
    section: '${ns}',
    title: { id: '${name}', en: '${name}' },
    order: 600,
    fields: [
      { key: '${ns}.page_size', type: 'number', title: { id: 'Baris per halaman', en: 'Rows per page' }, default: 20, min: 5, max: 200 },
      { key: '${ns}.greeting', type: 'string', title: { id: 'Sapaan widget', en: 'Widget greeting' }, default: 'Halo dari ${name}', public: true, max: 120 },
    ],
  },
]);
`;
  const i18n = (loc: 'id' | 'en') =>
    JSON.stringify(
      {
        [`${ns}.${plural}.title`]: title(plural),
        [`${ns}.${plural}.new`]: loc === 'id' ? `${Res} baru` : `New ${Res}`,
        [`${ns}.${plural}.empty`]: loc === 'id' ? `Belum ada ${plural}.` : `No ${plural} yet.`,
        [`${ns}.${plural}.saved`]: loc === 'id' ? 'Tersimpan.' : 'Saved.',
        [`${ns}.widget.title`]: title(plural),
      },
      null,
      2,
    );
  files['i18n/id.json'] = `${i18n('id')}\n`;
  files['i18n/en.json'] = `${i18n('en')}\n`;

  files['api/schemas.ts'] = `import { t } from 'elysia';

/** Body schemas shared by the API routes AND the dashboard forms (L-17). */
export const ${Res}Body = t.Object({
${fields.map((f) => `  ${camel(f.name)}: ${tbox(f)},`).join('\n')}
});
export const ${Res}UpdateBody = t.Partial(${Res}Body);
`;
  files['api/routes.ts'] = `import { type AuthState, clientIp } from '@app/api/plugins/auth';
import { requestContext } from '@app/api/plugins/request-context';
import { permission, tenantContext } from '@app/api/plugins/tenancy';
import { writeAudit } from '@core/auth';
import { errorResponses, fail, Id, OkSchema, ok, PageSchema, page, pageMeta } from '@core/contracts';
import { and, eq, isNull, newId, schema, unsafeAcrossTenants } from '@core/db';
import { defineApiRoutes } from '@core/module-kit';
import { Elysia, t } from 'elysia';
import { ${Res}Body, ${Res}UpdateBody } from './schemas.ts';

/** API (extension point 2), mounted at /v1/m/${ns}. CRUD through the tenant facade; every mutation audited. */
type Row = typeof schema.${tableVar}.$inferSelect;
const ${Res} = t.Object({
  id: t.String(),
${fields.map((f) => `  ${camel(f.name)}: ${tsType(f)},`).join('\n')}
  createdAt: t.String(),
  updatedAt: t.String(),
});
const view = (r: Row) => ({
  id: r.id,
${fields.map((f) => `  ${camel(f.name)}: r.${f.name}${f.type === 'date' ? ` ? (r.${f.name} as Date).toISOString().slice(0, 10) : null` : ''},`).join('\n')}
  createdAt: r.created_at.toISOString(),
  updatedAt: r.updated_at.toISOString(),
});
const toRow = (b: Partial<typeof ${Res}Body.static>) => ({
${fields.map((f) => `  ...(b.${camel(f.name)} !== undefined ? { ${f.name}: ${f.type === 'date' ? `b.${camel(f.name)} ? new Date(b.${camel(f.name)}) : null` : `b.${camel(f.name)}`} } : {}),`).join('\n')}
});

export default defineApiRoutes(
  '${name}',
  new Elysia({ name: 'module:${ns}', tags: ['module:${ns}'] })
    .use(requestContext)
    .use(tenantContext)
    .get(
      '/${plural}',
      async ({ query, tenantState }) => {
        if (!tenantState?.tenant) return page([], pageMeta(1, 20, 0));
        const rows = await tenantState.tenant.select(schema.${tableVar}, isNull(schema.${tableVar}.deleted_at));
        const q = query.q?.toLowerCase();
        const list = rows
          .filter((r) => !q || String(r.${titleField?.name ?? 'id'} ?? '').toLowerCase().includes(q))
          .sort((a, b) => b.created_at.getTime() - a.created_at.getTime());
        const p = Math.max(1, Number(query.page ?? 1));
        const limit = Math.min(100, Math.max(1, Number(query.limit ?? 20)));
        return page(list.slice((p - 1) * limit, p * limit).map(view), pageMeta(p, limit, list.length));
      },
      { beforeHandle: permission('${perm}.read'), query: t.Object({ q: t.Optional(t.String()), page: t.Optional(t.String()), limit: t.Optional(t.String()) }), response: { 200: PageSchema(${Res}), ...errorResponses }, detail: { summary: 'List ${plural} of the active tenant' } },
    )
    .get(
      '/${plural}/:id',
      async ({ params, set, requestId, tenantState }) => {
        const row = tenantState?.tenant ? await tenantState.tenant.selectOne(schema.${tableVar}, and(eq(schema.${tableVar}.id, params.id), isNull(schema.${tableVar}.deleted_at))) : null;
        if (!row) { set.status = 404; return fail('not_found', '${Res} tidak ditemukan', requestId); }
        return ok(view(row));
      },
      { beforeHandle: permission('${perm}.read'), params: t.Object({ id: Id }), response: { 200: OkSchema(${Res}), ...errorResponses }, detail: { summary: 'One ${resource}' } },
    )
    .post(
      '/${plural}',
      async ({ auth, body, set, request, server, requestId, tenantState }) => {
        const tenant = tenantState?.tenant;
        if (!tenant || !tenantState.clientId) { set.status = 409; return fail('conflict', 'Tidak ada tenant aktif', requestId); }
        const id = newId();
        await tenant.insert(schema.${tableVar}, { id, ...toRow(body) } as never);
        const row = (await tenant.selectOne(schema.${tableVar}, eq(schema.${tableVar}.id, id))) as Row;
        await writeAudit(unsafeAcrossTenants(), { clientId: tenantState.clientId, actorId: (auth as AuthState | null)?.user.id ?? null, action: '${perm}.create', resource: '${perm}', resourceId: id, ip: clientIp(request, server), requestId, after: view(row) });
        set.status = 201;
        return ok(view(row));
      },
      { beforeHandle: permission('${perm}.create'), body: ${Res}Body, response: { 201: OkSchema(${Res}), ...errorResponses }, detail: { summary: 'Create a ${resource}' } },
    )
    .put(
      '/${plural}/:id',
      async ({ auth, params, body, set, request, server, requestId, tenantState }) => {
        const tenant = tenantState?.tenant;
        const before = tenant ? await tenant.selectOne(schema.${tableVar}, and(eq(schema.${tableVar}.id, params.id), isNull(schema.${tableVar}.deleted_at))) : null;
        if (!tenant || !before || !tenantState.clientId) { set.status = 404; return fail('not_found', '${Res} tidak ditemukan', requestId); }
        const patch = toRow(body);
        if (Object.keys(patch).length) await tenant.update(schema.${tableVar}, patch as never, eq(schema.${tableVar}.id, before.id));
        const after = (await tenant.selectOne(schema.${tableVar}, eq(schema.${tableVar}.id, before.id))) as Row;
        await writeAudit(unsafeAcrossTenants(), { clientId: tenantState.clientId, actorId: (auth as AuthState | null)?.user.id ?? null, action: '${perm}.edit', resource: '${perm}', resourceId: before.id, ip: clientIp(request, server), requestId, before: view(before), after: view(after) });
        return ok(view(after));
      },
      { beforeHandle: permission('${perm}.edit'), params: t.Object({ id: Id }), body: ${Res}UpdateBody, response: { 200: OkSchema(${Res}), ...errorResponses }, detail: { summary: 'Edit a ${resource}' } },
    )
    .delete(
      '/${plural}/:id',
      async ({ auth, params, set, request, server, requestId, tenantState }) => {
        const tenant = tenantState?.tenant;
        const row = tenant ? await tenant.selectOne(schema.${tableVar}, and(eq(schema.${tableVar}.id, params.id), isNull(schema.${tableVar}.deleted_at))) : null;
        if (!tenant || !row || !tenantState.clientId) { set.status = 404; return fail('not_found', '${Res} tidak ditemukan', requestId); }
        await tenant.update(schema.${tableVar}, { deleted_at: new Date() } as never, eq(schema.${tableVar}.id, row.id));
        await writeAudit(unsafeAcrossTenants(), { clientId: tenantState.clientId, actorId: (auth as AuthState | null)?.user.id ?? null, action: '${perm}.delete', resource: '${perm}', resourceId: row.id, ip: clientIp(request, server), requestId, before: view(row) });
        return ok({ deleted: true as const });
      },
      { beforeHandle: permission('${perm}.manage'), params: t.Object({ id: Id }), response: { 200: OkSchema(t.Object({ deleted: t.Literal(true) })), ...errorResponses }, detail: { summary: 'Soft-delete a ${resource}' } },
    ),
);
`;

  files['api/tools.ts'] = `import { isNull, schema } from '@core/db';
import { defineTools } from '@core/module-kit';
import { t } from 'elysia';

/**
 * AI / MCP tools (extension point 8, I-3). The core registry runs them ONLY for callers holding
 * \`permission\`, only while the module is enabled for the tenant, and with the tenant facade as
 * \`ctx.db\` — the module never checks any of that itself. \`input\` (TypeBox → JSON Schema) validates
 * the arguments and describes them to the model / MCP client from one declaration.
 */
export default defineTools('${name}', [
  {
    name: '${ns}.list_${plural}',
    description: {
      id: 'Daftar ${plural} tenant aktif, opsional difilter ${titleField?.name ?? 'name'} (q). Pakai saat pengguna bertanya ${plural} apa yang ada.',
      en: 'List the active tenant’s ${plural}, optionally filtered by ${titleField?.name ?? 'name'} (q). Use when the user asks which ${plural} exist.',
    },
    permission: '${perm}.read',
    readOnly: true,
    input: t.Object({
      q: t.Optional(t.String({ maxLength: 120 })),
      limit: t.Optional(t.Integer({ minimum: 1, maximum: 50, default: 20 })),
    }),
    run: async (input, { db }) => {
      const q = typeof input.q === 'string' ? input.q.trim() : '';
      const limit = typeof input.limit === 'number' ? input.limit : 20;
      const rows = await db.select(schema.${tableVar}, isNull(schema.${tableVar}.deleted_at));
      const hit = q ? rows.filter((r) => String(r.${titleField?.name ?? 'name'} ?? '').toLowerCase().includes(q.toLowerCase())) : rows;
      return { total: hit.length, ${plural}: hit.slice(0, limit).map((r) => ({ id: r.id, ${titleProp}: r.${titleField?.name ?? 'name'} })) };
    },
  },
]);
`;
  files['hooks.ts'] = `import { logger } from '@core/logger';
import { defineHooks } from '@core/module-kit';

/** Event hooks (extension point 9). A failing handler is logged, never re-thrown to the emitter (G-7). */
export default defineHooks('${name}', {
  'user.created': async (payload, ctx) => {
    logger.info('${ns}: user created', { userId: payload.userId, clientId: payload.clientId, requestId: ctx.requestId });
  },
});
`;
  files['jobs.ts'] = `import { count, isNull, schema, unsafeAcrossTenants } from '@core/db';
import { logger } from '@core/logger';
import { defineJobs } from '@core/module-kit';

/** Scheduled job (extension point 12): runs once per interval across all instances. */
export default defineJobs('${name}', [
  {
    name: '${ns}.heartbeat',
    every: '1h',
    description: { id: 'Menghitung ${plural}', en: 'Counts ${plural}' },
    run: async ({ instanceId }) => {
      const [row] = await unsafeAcrossTenants().select({ n: count() }).from(schema.${tableVar}).where(isNull(schema.${tableVar}.deleted_at));
      logger.info('${ns}: heartbeat', { ${plural}: Number(row?.n ?? 0), instanceId });
    },
  },
]);
`;
  files['widgets.ts'] = `import { defineWidgets } from '@core/module-kit';

/** Dashboard widget (extension point 11), filtered by permission on the server. */
export default defineWidgets('${name}', [
  { id: '${ns}.summary', title: { id: '${title(plural)}', en: '${title(plural)}' }, component: 'web/widgets/Summary.svelte', permission: '${perm}.read', order: 200, size: 'sm' },
]);
`;
  files['web/widgets/Summary.svelte'] = `<script lang="ts">
let { context }: { context?: { locale: string } } = $props();
</script>

<div class="grid gap-2 text-sm" data-testid="widget-${ns}">
  <a href="/m/${ns}/${plural}" class="font-medium">{context?.locale === 'en' ? 'Manage ${plural}' : 'Kelola ${plural}'} →</a>
</div>
`;
  files['seed.ts'] = `import { and, type Db, eq, newId, schema } from '@core/db';
import { defineSeed } from '@core/module-kit';

/** Idempotent seed (O-3): one sample row for the default tenant, created only when absent. */
export default defineSeed('${name}', async ({ db: raw, tenantId, log }) => {
  const db = raw as Db;
  const [row] = await db.select({ id: schema.${tableVar}.id }).from(schema.${tableVar}).where(and(eq(schema.${tableVar}.client_id, tenantId), eq(schema.${tableVar}.${titleField?.name ?? 'name'}, ${titleField?.type === 'number' ? '1' : `'Contoh ${resource}'`}))).limit(1);
  if (row) return;
  await db.insert(schema.${tableVar}).values({ id: newId(), client_id: tenantId, ${titleField?.name ?? 'name'}: ${titleField?.type === 'number' ? '1' : `'Contoh ${resource}'`} } as never);
  log('1 baris contoh dibuat');
});
`;

  // ---- dashboard pages (extension point 3) ----
  files[`web/routes/${plural}/_form.ts`] = `import type { FieldDef } from '@core/ui';

export const fields: FieldDef[] = [
${fields.map((f) => `  ${fieldDef(f)},`).join('\n')}
];
`;
  files[`web/routes/${plural}/+page.server.ts`] = `import type { ServerLoad } from '@sveltejs/kit';
import { error } from '@sveltejs/kit';
import { apiFor } from '$lib/server/session';

export const _layoutVariant = 'wide';

export const load: ServerLoad = async (event) => {
  const q = event.url.searchParams.get('q') ?? '';
  const pageNo = event.url.searchParams.get('page') ?? '1';
  const res = await apiFor(event).v1.m.${ns}.${plural}.get({ query: { ...(q ? { q } : {}), page: pageNo, limit: '20' } });
  if (!res.data?.success) error(res.status, res.status === 403 ? 'Anda tidak punya izin' : 'Data tidak bisa dimuat');
  return { rows: res.data.data, meta: res.data.meta, q, saved: event.url.searchParams.get('saved') };
};
`;
  files[`web/routes/${plural}/+page.svelte`] = `<script lang="ts">
import { Button, Icon, Table } from '@core/ui';
import { useT } from '$lib/i18n';
import { hasPermission } from '$lib/permissions';

let { data } = $props();
const t = useT();
const can = (p: string) => data.user.isSuperadmin || hasPermission(data.permissions, p);
/** Eden revives ISO dates into Date objects — show them as YYYY-MM-DD. */
const cell = (v: unknown) => (v instanceof Date ? v.toISOString().slice(0, 10) : (v ?? '—'));
</script>

<svelte:head><title>{t('${ns}.${plural}.title')}</title></svelte:head>

<div class="page">
  <div class="flex flex-wrap items-center justify-between gap-3">
    <h1>{t('${ns}.${plural}.title')}</h1>
    <div class="flex gap-2">
      <form method="GET" class="flex gap-1"><input name="q" value={data.q} placeholder={t('common.search')} class="h-9 rounded-md border border-input bg-background px-3 text-sm" /><Button type="submit" variant="outline" size="sm"><Icon name="search" size={16} /></Button></form>
      {#if can('${perm}.create')}<Button href="/m/${ns}/${plural}/new" size="sm"><Icon name="plus" size={16} />{t('${ns}.${plural}.new')}</Button>{/if}
    </div>
  </div>
  {#if data.saved === 'deleted'}<p class="notice">{t('common.delete')}: OK</p>{/if}
  <Table caption={t('${ns}.${plural}.title')}>
    <thead><tr>${fields
      .slice(0, 4)
      .map((f) => `<th>${title(f.name)}</th>`)
      .join('')}<th></th></tr></thead>
    <tbody>
      {#each data.rows as r (r.id)}
        <tr>
${fields
  .slice(0, 4)
  .map(
    (f, i) =>
      `          <td${i === 0 ? ' class="font-medium"' : ''}>{${f.type === 'boolean' ? `r.${camel(f.name)} ? '✓' : '—'` : `cell(r.${camel(f.name)})`}}</td>`,
  )
  .join('\n')}
          <td class="text-right"><a href={\`/m/${ns}/${plural}/\${r.id}\`}>{can('${perm}.edit') ? t('common.edit') : t('common.view')}</a></td>
        </tr>
      {:else}
        <tr><td colspan="${Math.min(fields.length, 4) + 1}" class="py-8 text-center text-muted-foreground">{t('${ns}.${plural}.empty')}</td></tr>
      {/each}
    </tbody>
  </Table>
  <p class="text-sm text-muted-foreground">{data.meta.total} · {data.meta.page}/{data.meta.totalPages}</p>
</div>
`;
  const actionPrelude = `import { formToObject, validateForm } from '@core/contracts';
import type { Actions } from '@sveltejs/kit';
import { redirect } from '@sveltejs/kit';
import { actionFailure, apiFor, checkCsrf, unwrap } from '$lib/server/session';
`;
  const boolNames = fields.filter((f) => f.type === 'boolean').map((f) => camel(f.name));
  const nullable = fields
    .filter((f) => !f.required && f.type !== 'boolean')
    .map((f) => camel(f.name));
  const normalize = `    const raw = formToObject(form, { nullable: ${JSON.stringify(nullable)} });
    const input = { ...raw${boolNames.map((b) => `, ${b}: raw.${b} !== undefined`).join('')} };`;
  files[`web/routes/${plural}/new/+page.server.ts`] =
    `${actionPrelude}import { ${Res}Body } from '../../../../api/schemas.ts';

export const actions: Actions = {
  default: async (event) => {
    const form = await event.request.formData();
${normalize}
    if (!checkCsrf(event, form)) return actionFailure({ status: 403, code: 'csrf_failed', message: 'Sesi formulir kedaluwarsa — muat ulang halaman' }, raw);
    const v = validateForm(${Res}Body, input); // the API's own schema (L-17)
    if (!v.ok) return actionFailure({ status: 422, code: 'validation_failed', message: 'Periksa isian yang ditandai', details: v.errors }, raw);
    const r = unwrap<{ success: true; data: { id: string } }>(await apiFor(event).v1.m.${ns}.${plural}.post(v.value));
    if (!r.ok) return actionFailure(r.failure, raw);
    redirect(303, \`/m/${ns}/${plural}/\${r.data.data.id}?saved=1\`);
  },
};
`;
  files[`web/routes/${plural}/new/+page.svelte`] = `<script lang="ts">
import { FormBuilder } from '@core/ui';
import { useT } from '$lib/i18n';
import { fields } from '../_form.ts';

let { data, form } = $props();
const t = useT();
const fieldErrors = $derived((form?.details && typeof form.details === 'object' ? form.details : {}) as Record<string, string>);
</script>

<svelte:head><title>{t('${ns}.${plural}.new')}</title></svelte:head>

<div class="page">
  <h1>{t('${ns}.${plural}.new')}</h1>
  <FormBuilder {fields} values={(form?.values as Record<string, unknown> | undefined) ?? {}} errors={fieldErrors} csrf={data.csrf} columns={2} submitLabel={t('common.save')} cancelHref="/m/${ns}/${plural}" error={form?.error && Object.keys(fieldErrors).length === 0 ? form.error : null} />
</div>
`;
  files[`web/routes/${plural}/[id]/+page.server.ts`] =
    `import { formToObject, validateForm } from '@core/contracts';
import type { Actions, ServerLoad } from '@sveltejs/kit';
import { error, redirect } from '@sveltejs/kit';
import { actionFailure, apiFor, checkCsrf, unwrap } from '$lib/server/session';
import { ${Res}UpdateBody } from '../../../../api/schemas.ts';

export const load: ServerLoad = async (event) => {
  const id = String(event.params.id ?? '');
  const res = await apiFor(event).v1.m.${ns}.${plural}({ id }).get();
  if (!res.data?.success) error(res.status === 404 ? 404 : res.status, '${Res} tidak ditemukan');
  return { row: res.data.data, saved: event.url.searchParams.has('saved') };
};

export const actions: Actions = {
  save: async (event) => {
    const form = await event.request.formData();
    const id = String(event.params.id ?? '');
${normalize}
    if (!checkCsrf(event, form)) return actionFailure({ status: 403, code: 'csrf_failed', message: 'Sesi formulir kedaluwarsa — muat ulang halaman' }, raw);
    const v = validateForm(${Res}UpdateBody, input);
    if (!v.ok) return actionFailure({ status: 422, code: 'validation_failed', message: 'Periksa isian yang ditandai', details: v.errors }, raw);
    const r = unwrap(await apiFor(event).v1.m.${ns}.${plural}({ id }).put(v.value));
    if (!r.ok) return actionFailure(r.failure, raw);
    return { saved: true };
  },
  delete: async (event) => {
    const form = await event.request.formData();
    const id = String(event.params.id ?? '');
    if (!checkCsrf(event, form)) return actionFailure({ status: 403, code: 'csrf_failed', message: 'Sesi formulir kedaluwarsa — muat ulang halaman' });
    const r = unwrap(await apiFor(event).v1.m.${ns}.${plural}({ id }).delete());
    if (!r.ok) return actionFailure(r.failure);
    redirect(303, '/m/${ns}/${plural}?saved=deleted');
  },
};
`;
  files[`web/routes/${plural}/[id]/+page.svelte`] = `<script lang="ts">
import { Button, Card, Csrf, FormBuilder, Icon } from '@core/ui';
import { useT } from '$lib/i18n';
import { hasPermission } from '$lib/permissions';
import { fields } from '../_form.ts';

let { data, form } = $props();
const t = useT();
const can = (p: string) => data.user.isSuperadmin || hasPermission(data.permissions, p);
const r = $derived(data.row);
const fieldErrors = $derived((form?.details && typeof form.details === 'object' ? form.details : {}) as Record<string, string>);
</script>

<svelte:head><title>{r.${titleProp} ?? r.id}</title></svelte:head>

<div class="page">
  <h1>{r.${titleProp} ?? r.id}</h1>
  <Card>
    <FormBuilder {fields} values={r as unknown as Record<string, unknown>} errors={fieldErrors} csrf={data.csrf} action="?/save" columns={2} readonly={!can('${perm}.edit')} cancelHref="/m/${ns}/${plural}" cancelLabel={t('common.back')} notice={form?.saved || data.saved ? t('${ns}.${plural}.saved') : null} error={form?.error && Object.keys(fieldErrors).length === 0 ? form.error : null} />
  </Card>
  {#if can('${perm}.manage')}
    <Card><form method="POST" action="?/delete"><Csrf token={data.csrf} /><Button type="submit" variant="destructive"><Icon name="trash" size={16} />{t('common.delete')}</Button></form></Card>
  {/if}
</div>
`;

  if (s.withPublic) {
    files['public.ts'] = `import { definePublicRoutes } from '@core/module-kit';

/** Public page (extension point 13) at /${ns}, no session, public layout of the active theme. */
export default definePublicRoutes('${name}', [{ path: '/${ns}', dir: 'web/public/home', sitemap: true }]);
`;
    files['web/public/home/+page.svelte'] =
      `<svelte:head><title>${name}</title><meta name="description" content="${name} — public page from a module (extension point 13)." /></svelte:head>
<section class="mx-auto max-w-3xl px-4 py-16" data-testid="public-${ns}">
  <h1>${name}</h1>
  <p class="mt-2 text-muted-foreground">Halaman publik modul ${name}, ter-SSR dengan layout publik tema aktif.</p>
</section>
`;
  }

  // ---- integration test inside the module (runs with INTEGRATION=1) ----
  const sample = fields
    .map(
      (f) =>
        `${camel(f.name)}: ${f.type === 'number' ? '42' : f.type === 'boolean' ? 'true' : f.type === 'date' ? "'2026-01-31'" : f.type === 'select' ? `'${f.options?.[0] ?? ''}'` : `'Contoh ${f.name}'`}`,
    )
    .join(', ');
  files[`test/integration/${ns}.test.ts`] =
    `import { beforeAll, describe, expect, test } from 'bun:test';
import { app } from '@app/api/app';
import { runSeed } from '@core/auth';
import { unsafeAcrossTenants } from '@core/db';

/** Generated by modgen: CRUD of ${plural} through the real app (INTEGRATION=1). */
const enabled = process.env.INTEGRATION === '1';
const ORIGIN = 'http://api.test';
const TOKEN = 'C'.repeat(43);
const run = Date.now();
const email = \`${ns}-\${run}@example.test\`;
const password = 'a generated module password';
const call = (path: string, init: RequestInit = {}, cookies: string[] = []) => {
  const headers = new Headers(init.headers);
  headers.set('origin', ORIGIN);
  headers.set('cookie', [\`dab_csrf=\${TOKEN}\`, ...cookies].join('; '));
  headers.set('x-csrf-token', TOKEN);
  headers.set('x-forwarded-for', \`10.99.\${Math.floor(run / 1000) % 250}.\${run % 250}\`);
  if (init.body && !headers.has('content-type')) headers.set('content-type', 'application/json');
  return app.handle(new Request(\`\${ORIGIN}\${path}\`, { ...init, headers }));
};
const json = (r: Response) => r.json() as Promise<{ success: boolean; data?: Record<string, unknown> }>;

describe.skipIf(!enabled)('${name} module CRUD', () => {
  let admin = '';
  beforeAll(async () => {
    if (!enabled) return;
    await runSeed(unsafeAcrossTenants(), { adminEmail: email, adminPassword: password });
    const res = await call('/v1/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) });
    admin = res.headers.getSetCookie().find((c) => c.startsWith('dab_session='))?.split(';')[0] ?? '';
  });
  test('create → read → update → delete', async () => {
    const created = await call('/v1/m/${ns}/${plural}', { method: 'POST', body: JSON.stringify({ ${sample} }) }, [admin]);
    expect(created.status).toBe(201);
    const id = String((await json(created)).data?.id);
    expect((await call(\`/v1/m/${ns}/${plural}/\${id}\`, {}, [admin])).status).toBe(200);
    const list = await json(await call('/v1/m/${ns}/${plural}', {}, [admin]));
    expect((list.data as unknown as { id: string }[]).some((r) => r.id === id)).toBe(true);
    expect((await call(\`/v1/m/${ns}/${plural}/\${id}\`, { method: 'PUT', body: JSON.stringify({ ${camel(titleField?.name ?? 'name')}: ${titleField?.type === 'number' ? '7' : "'Diubah'"} }) }, [admin])).status).toBe(200);
    expect((await call(\`/v1/m/${ns}/${plural}/\${id}\`, { method: 'DELETE' }, [admin])).status).toBe(200);
    expect((await call(\`/v1/m/${ns}/${plural}/\${id}\`, {}, [admin])).status).toBe(404);
    expect((await call('/v1/m/${ns}/${plural}')).status).toBe(401); // anonymous refused
  });
});
`;
  files['README.md'] = `# ${name}

Modul yang dibuat \`bun modgen\`. Semua titik perluasan yang dipakai sudah berjalan: tabel, izin, menu,
konfigurasi, i18n, API + skema bersama, tool AI/MCP, halaman list/form, widget, hook, job, seed, dan tes integrasi.
Ubah sesuai kebutuhan — ini kode Anda, bukan kode core. Lihat \`docs/MODULES.md\` dan \`docs/FIRST-MODULE.md\`.
`;
  return files;
}
