#!/usr/bin/env sh
# Remove the module generated by `bun run modgen:ci` (or MODGEN_GUARD_NAME) and restore the tree:
# modules.json, bun.lock and the migrations come back from HEAD, then the registries are re-synced.
set -eu
cd "$(dirname "$0")/../.."
NAME="${MODGEN_GUARD_NAME:-CiProbe}"
rm -rf "modules/$NAME"
git checkout -- modules.json bun.lock packages/db/migrations
git clean -fdq packages/db/migrations
bun install --no-summary >/dev/null
bun run modules:sync >/dev/null
echo "modgen-cleanup: modules/$NAME dihapus, pohon dipulihkan"
