export {
  CORE_ICONS,
  CORE_VARIANTS,
  type CoreVariant,
  FALLBACK_THEME,
  ICON_SETS,
  type IconSetDef,
  isMode,
  type LayoutDef,
  type LayoutResolution,
  type LayoutVariant,
  type LocalizedText,
  layoutById,
  layouts,
  type Mode,
  REGIONS,
  registerLayout,
  registerTheme,
  resolveLayout,
  resolveTheme,
  type ShellKind,
  type ThemeManifest,
  type ThemeResolution,
  type ThemeResolutionInput,
  themeById,
  themes,
} from './registry.ts';
