import type { ColumnDef, TableDef } from '../descriptor.ts';

/**
 * Emitters: descriptor → TypeScript source of a Drizzle schema, one function per dialect.
 *
 * Pure functions (string in, string out) so they can be tested without touching disk, and
 * so the §4.3 portability rules are visible in one place: the mapping below IS the PRD's
 * "type portability rules" table, expressed as code.
 */

export type Dialect = 'mysql' | 'pg';

const HEADER = (dialect: Dialect): string =>
  `// GENERATED by \`bun db:codegen\` from packages/db/schema/*.def.ts — DO NOT edit by hand.
// Dialect: ${dialect}. The descriptors are the source of truth; change them and regenerate.
/* biome-ignore-all lint: generated file */
`;

// ---------------------------------------------------------------------------
// MySQL / MariaDB
// ---------------------------------------------------------------------------

const MYSQL_IMPORTS = [
  'bigint',
  'boolean',
  'datetime',
  'decimal',
  'index',
  'int',
  'json',
  'mysqlTableCreator',
  'uniqueIndex',
] as const;
const MYSQL_CUSTOM = [
  'asciiVarchar',
  'utf8LongText',
  'utf8Text',
  'utf8Varchar',
  'uuidChar',
] as const;

function mysqlColumn(name: string, c: ColumnDef): string {
  const t = c.type;
  let e: string;
  switch (t.kind) {
    case 'uuid':
      e = `uuidChar('${name}')`;
      break;
    case 'varchar':
      e = t.identifier
        ? `asciiVarchar('${name}', { length: ${t.length} })`
        : `utf8Varchar('${name}', { length: ${t.length} })`;
      break;
    case 'enum': // native enums are forbidden — varchar + application constraint (§4.3)
      e = `utf8Varchar('${name}', { length: ${t.length} })`;
      break;
    case 'text':
      e = `utf8Text('${name}')`;
      break;
    case 'longtext':
      e = `utf8LongText('${name}')`;
      break;
    case 'int':
      e = `int('${name}')`;
      break;
    case 'bigint':
      e = `bigint('${name}', { mode: 'number' })`;
      break;
    case 'boolean':
      e = `boolean('${name}')`; // tinyint(1); Drizzle normalizes
      break;
    case 'datetime':
      e = `datetime('${name}', { fsp: 3 })`; // always UTC
      break;
    case 'json':
      e = `json('${name}')`;
      break;
    case 'decimal':
      e = `decimal('${name}', { precision: 18, scale: 4 })`;
      break;
  }
  return e + modifiers(c, { now: '.default(sql`CURRENT_TIMESTAMP(3)`)' });
}

export function emitMysql(tables: readonly TableDef[]): string {
  const sorted = sortTables(tables);
  const body = sorted.map((t) => emitTable(t, mysqlColumn)).join('\n\n');
  return `${HEADER('mysql')}
import { sql } from 'drizzle-orm';
import { ${MYSQL_IMPORTS.join(', ')} } from 'drizzle-orm/mysql-core';
import { ${MYSQL_CUSTOM.join(', ')} } from '../dialect/mysql-types.ts';

// O-2: optional table prefix so several apps can share one database.
const TABLE_PREFIX = process.env.TABLE_PREFIX ?? '';
const table = mysqlTableCreator((name) => \`\${TABLE_PREFIX}\${name}\`);

${body}

${emitFooter(sorted)}`;
}

// ---------------------------------------------------------------------------
// PostgreSQL
// ---------------------------------------------------------------------------

const PG_IMPORTS = [
  'bigint',
  'boolean',
  'index',
  'integer',
  'jsonb',
  'numeric',
  'pgTableCreator',
  'text',
  'timestamp',
  'uniqueIndex',
  'uuid',
  'varchar',
] as const;

function pgColumn(name: string, c: ColumnDef): string {
  const t = c.type;
  let e: string;
  switch (t.kind) {
    case 'uuid':
      e = `uuid('${name}')`;
      break;
    case 'varchar':
    case 'enum':
      e = `varchar('${name}', { length: ${t.length} })`;
      break;
    case 'text':
    case 'longtext':
      e = `text('${name}')`;
      break;
    case 'int':
      e = `integer('${name}')`;
      break;
    case 'bigint':
      e = `bigint('${name}', { mode: 'number' })`;
      break;
    case 'boolean':
      e = `boolean('${name}')`;
      break;
    case 'datetime':
      e = `timestamp('${name}', { withTimezone: true, precision: 3, mode: 'date' })`;
      break;
    case 'json':
      e = `jsonb('${name}')`;
      break;
    case 'decimal':
      e = `numeric('${name}', { precision: 18, scale: 4 })`;
      break;
  }
  return e + modifiers(c, { now: '.defaultNow()' });
}

export function emitPg(tables: readonly TableDef[]): string {
  const sorted = sortTables(tables);
  const body = sorted.map((t) => emitTable(t, pgColumn)).join('\n\n');
  return `${HEADER('pg')}
import { ${PG_IMPORTS.join(', ')} } from 'drizzle-orm/pg-core';

// O-2: optional table prefix so several apps can share one database.
const TABLE_PREFIX = process.env.TABLE_PREFIX ?? '';
const table = pgTableCreator((name) => \`\${TABLE_PREFIX}\${name}\`);

${body}

${emitFooter(sorted)}`;
}

// ---------------------------------------------------------------------------
// shared
// ---------------------------------------------------------------------------

function modifiers(c: ColumnDef, opt: { now: string }): string {
  let m = '';
  if (c.primaryKey) m += '.primaryKey()';
  else if (!c.nullable) m += '.notNull()';
  if (c.default) {
    m += c.default.kind === 'now' ? opt.now : `.default(${JSON.stringify(c.default.value)})`;
  }
  if (c.onUpdateNow) m += '.$onUpdate(() => new Date())';
  if (c.references) {
    // Lazy reference: the target const may be declared later in the file (tables are sorted by name).
    m += `.references(() => ${camel(c.references.table)}.id, { onDelete: '${c.references.onDelete}' })`;
  }
  return m;
}

function emitTable(t: TableDef, column: (name: string, c: ColumnDef) => string): string {
  const cols = Object.entries(t.columns)
    .map(([name, c]) => `    ${name}: ${column(name, c)},`)
    .join('\n');
  const idx = t.indexes
    .map(
      (ix) =>
        `    ${ix.unique ? 'uniqueIndex' : 'index'}('${ix.name}').on(${ix.columns.map((c) => `t.${c}`).join(', ')}),`,
    )
    .join('\n');
  const tenantNote = t.tenant
    ? ` // tenant-scoped${t.tenant.nullable ? ' (client_id NULL = global, E-2)' : ''}`
    : ' // global';
  return `export const ${camel(t.name)} = table(
  '${t.name}',${tenantNote}
  {
${cols}
  },
  (t) => [
${idx}
  ],
);`;
}

function emitFooter(tables: readonly TableDef[]): string {
  const names = tables.map((t) => camel(t.name));
  const tenant = tables.filter((t) => t.tenant).map((t) => `'${t.name}'`);
  return `/** All tables — passed to \`drizzle(client, { schema })\` so relations and types are complete. */
export const schema = { ${names.join(', ')} } as const;

/** Names of tenant-scoped tables. Used by the data-layer tenant guard (B-3) to inject the client_id filter. */
export const tenantTables: ReadonlySet<string> = new Set([${tenant.join(', ')}]);
`;
}

function sortTables(tables: readonly TableDef[]): TableDef[] {
  const names = tables.map((t) => t.name);
  const dup = names.find((n, i) => names.indexOf(n) !== i);
  if (dup) throw new Error(`codegen: tabel "${dup}" didefinisikan dua kali`);
  for (const t of tables) {
    for (const [col, c] of Object.entries(t.columns)) {
      if (c.references && !names.includes(c.references.table)) {
        throw new Error(
          `codegen: ${t.name}.${col} merujuk tabel "${c.references.table}" yang tidak ada`,
        );
      }
    }
  }
  return [...tables].sort((a, b) => a.name.localeCompare(b.name));
}

export function camel(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}
