#!/usr/bin/env bun
/**
 * `bun run layout:variants` — collects `export const _layoutVariant = '<variant>'` and
 * `export const _aside = '<id>'` (SvelteKit allows custom page exports only with a `_` prefix)
 * from every page module (apps/web/src/routes/**\/+page.ts | +page.server.ts, following module
 * shims into modules/<Name>/web/routes) into generated maps keyed by SvelteKit route id.
 *
 * Why generated: the shell layout must know a page's variant AND its side content BEFORE that
 * page loads, so both are resolved and code-split on the server (PRD §4.8, Decision K). A page
 * cannot hand the shell a snippet — the shell renders first — so it names one instead.
 * Runs as part of `bootstrap`; the output is gitignored like the other generated files.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const routes = join(root, 'apps/web/src/routes');
const out = join(root, 'apps/web/src/generated/layout-variants.ts');
const routesOut = join(root, 'packages/settings/src/generated/routes.ts');
const routesOutWeb = join(root, 'apps/web/src/generated/routes.ts');

function walk(dir: string): string[] {
  const files: string[] = [];
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    if (statSync(p).isDirectory()) files.push(...walk(p));
    else files.push(p);
  }
  return files;
}

/** SvelteKit route id: directory relative to routes/, leading slash, groups kept. */
function routeId(file: string): string {
  const rel = relative(routes, dirname(file)).split('\\').join('/');
  return rel === '' ? '/' : `/${rel}`;
}

const VARIANT_RE = /export\s+const\s+_layoutVariant\s*=\s*['"]([a-z][a-z0-9_.-]*)['"]/;
const ASIDE_RE = /export\s+const\s+_aside\s*=\s*['"]([a-z][a-z0-9_.-]*)['"]/;
const SHIM_RE = /export \* from '([^']+)'/;

const map: Record<string, string> = {};
const asides: Record<string, string> = {};
const concretePaths = new Set<string>();
const concreteIds = new Set<string>(); // lint: a page must never name a concrete layout (L-9)
const layoutIds = new Set(
  (
    JSON.parse(readFileSync(join(root, 'packages/ui-theme/layouts/registry.json'), 'utf8')) as {
      layouts: { id: string }[];
    }
  ).layouts.map((l) => l.id),
);

for (const file of walk(routes)) {
  // `join` yields `\` separators on Windows; match on a POSIX-normalised copy, otherwise both
  // generated maps come out empty there — and an empty route registry makes every `route` setting
  // (app.landing_route above all) fail validation, so `/` silently falls back to the built-in page.
  const posix = file.split('\\').join('/');
  // Route registry (§4.7): every page, as a concrete path — groups stripped, param routes skipped.
  if (/\/\+page\.svelte$/.test(posix)) {
    const id = routeId(file);
    if (!/\[/.test(id)) {
      const path = id.replace(/\/\([^)]+\)/g, '') || '/';
      concretePaths.add(path === '' ? '/' : path);
    }
  }
  if (!/\/\+page(\.server)?\.ts$/.test(posix)) continue;
  let src = readFileSync(file, 'utf8');
  const shim = SHIM_RE.exec(src);
  if (shim?.[1]?.startsWith('.')) {
    const target = resolve(dirname(file), shim[1]);
    if (existsSync(target)) src = readFileSync(target, 'utf8');
  }
  const m = VARIANT_RE.exec(src);
  if (m?.[1]) {
    const id = routeId(file);
    if (map[id] && map[id] !== m[1]) {
      console.error(`layout:variants: ${id} mendeklarasikan dua varian (${map[id]} vs ${m[1]})`);
      process.exit(1);
    }
    map[id] = m[1];
    if (layoutIds.has(m[1])) concreteIds.add(`${id} → ${m[1]}`);
  }
  const a = ASIDE_RE.exec(src);
  if (a?.[1]) {
    const id = routeId(file);
    if (asides[id] && asides[id] !== a[1]) {
      console.error(`layout:variants: ${id} mendeklarasikan dua aside (${asides[id]} vs ${a[1]})`);
      process.exit(1);
    }
    asides[id] = a[1];
  }
}

if (concreteIds.size) {
  // Allowed as an escape hatch, but flagged: such a page is no longer theme-neutral (L-9).
  for (const c of concreteIds)
    console.warn(`layout:variants: PERINGATAN halaman menyematkan id layout konkret: ${c}`);
}

const body = `// GENERATED by \`bun run layout:variants\` — DO NOT edit by hand.
/* biome-ignore-all lint: generated file */

/** SvelteKit route id → layoutVariant declared by that page (PRD §4.8, Decision K). */
export const layoutVariants: Readonly<Record<string, string>> = ${JSON.stringify(map, null, 2)};

/** SvelteKit route id → aside id declared by that page; the shell resolves it like the layout. */
export const pageAsides: Readonly<Record<string, string>> = ${JSON.stringify(asides, null, 2)};
`;
await Bun.write(out, body);
const routeList = [...concretePaths].sort();
const routesBody = `// GENERATED by \`bun run layout:variants\` — DO NOT edit by hand.
/* biome-ignore-all lint: generated file */

/** Concrete web route paths (no params), core + modules — for validating \`route\` settings (§4.7). */
export const webRoutes: readonly string[] = ${JSON.stringify(routeList, null, 2)};
`;
await Bun.write(routesOut, routesBody);
await Bun.write(routesOutWeb, routesBody);
console.log(`layout:variants: ${routeList.length} route konkret → ${relative(root, routesOut)}`);
console.log(
  `layout:variants: ${Object.keys(map).length} halaman mendeklarasikan varian, ${Object.keys(asides).length} mendeklarasikan aside → ${relative(root, out)}`,
);
