#!/usr/bin/env bun
/**
 * `bun db:codegen` — descriptors → Drizzle schema per dialect + active-dialect selection.
 *
 * Always writes BOTH schemas (drizzle-kit needs both for tier-1 migrations), then writes
 * `generated/active.ts` re-exporting the dialect selected by DB_DIALECT. Application code
 * only imports `@core/db`, so its types are concrete for one dialect rather than an
 * uncallable union. Consequence: CI runs the typecheck once per dialect.
 *
 * Deterministic: identical input → byte-identical output. Outputs are gitignored.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tables } from '../schema/index.ts';
import { emitMysql, emitPg } from '../src/codegen/emit.ts';

const OUT = join(import.meta.dir, '..', 'src', 'generated');

const rawDialect = process.env.DB_DIALECT ?? 'mysql';
const active = rawDialect === 'postgres' ? 'pg' : 'mysql'; // mariadb shares the mysql schema
if (!['mysql', 'mariadb', 'postgres'].includes(rawDialect)) {
  console.error(
    `db:codegen: DB_DIALECT="${rawDialect}" tidak dikenal (mysql | mariadb | postgres)`,
  );
  process.exit(1);
}

const activeSource = `// GENERATED by \`bun db:codegen\` — DO NOT edit by hand.
// Active dialect at generation time: ${rawDialect} → ${active} schema.
/* biome-ignore-all lint: generated file */
export * as schema from './schema.${active}.ts';
export { tenantTables } from './schema.${active}.ts';
export { createDb, type Db } from '../dialect/${active}-client.ts';
export const activeDialect = '${rawDialect}' as const;
`;

await mkdir(OUT, { recursive: true });

// Module tables arrive through `modules:sync` (G-2). When sync has not run yet (a fresh
// checkout typechecking only core) an empty registry keeps the import resolvable.
const moduleTablesFile = join(OUT, 'module-tables.ts');
if (!(await Bun.file(moduleTablesFile).exists())) {
  await Bun.write(
    moduleTablesFile,
    `// GENERATED placeholder — run \`bun modules:sync\` to populate.\n/* biome-ignore-all lint: generated file */\nimport type { TableDef } from '../descriptor.ts';\nexport const moduleTables: readonly TableDef[] = [];\n`,
  );
}
const { moduleTables } = await import('../src/generated/module-tables.ts');
const allTables = [...tables, ...moduleTables];

/**
 * Embed the committed migrations of the active family (Q-2, Q-4). The compiled api binary
 * carries no `packages/db/migrations` folder, so `runMigrations()` materialises these strings
 * into a temp folder for Drizzle's migrator — one code path for `bun db:migrate` and `api migrate`.
 * Only `*.sql` + `meta/_journal.json` are needed; snapshots stay on disk for drizzle-kit.
 */
const migrationsDir = join(import.meta.dir, '..', 'migrations', active);
const sqlFiles = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();
const journal = readFileSync(join(migrationsDir, 'meta', '_journal.json'), 'utf8');
const migrationsSource = `// GENERATED by \`bun db:codegen\` — DO NOT edit by hand.
// Committed migrations for the ${active} family, embedded so the compiled api binary can migrate (Q-2).
/* biome-ignore-all lint: generated file */
export const family = ${JSON.stringify(active)} as const;
export const journal: string = ${JSON.stringify(journal)};
export const files: ReadonlyArray<{ readonly name: string; readonly sql: string }> = [
${sqlFiles.map((f) => `  { name: ${JSON.stringify(f)}, sql: ${JSON.stringify(readFileSync(join(migrationsDir, f), 'utf8'))} },`).join('\n')}
];
`;

const files: Array<[string, string]> = [
  ['schema.mysql.ts', emitMysql(allTables)],
  ['schema.pg.ts', emitPg(allTables)],
  ['active.ts', activeSource],
  ['migrations.ts', migrationsSource],
];
for (const [name, content] of files) {
  await Bun.write(join(OUT, name), content);
}

console.log(
  `db:codegen: ${allTables.length} tabel (${tables.length} core + ${moduleTables.length} modul) → ${files.map(([n]) => n).join(', ')} (aktif: ${rawDialect}, ${sqlFiles.length} migrasi disematkan)`,
);
